### ISSUE TITLE
Revoking permission on cancellation appears to not be working

### ISSUE THREAD

**Issue by stevecomrie** [oof-bar/craft-membership#7]
Couldn't figure out what was going on, but I noticed that there is no event trigger in the entire plugin for `EVENT_AFTER_CANCEL_SUBSCRIPTION` which is the commerce action that gets called when a subscription is cancelled.

Kind of just seems like there's an entire block missing from the Membership.php file for:

```
Event::on(
    Subscriptions::class,
    Subscriptions::EVENT_AFTER_CANCEL_SUBSCRIPTION,
    function (SubscriptionEvent $event) {
        Membership::getInstance()->permissions->revokePermissionsForSubscription($event->subscription);
    });
```

**Comment by AugustMiller** [comment]
Hey, Steve! You're right, we don't use the "cancel" event because it’s not a good indicator of the actual subscription status—instead, we use `craft\commerce\services\Subscriptions::EVENT_AFTER_EXPIRE_SUBSCRIPTION`, which is emitted in response to Stripe web hooks.

**Cancellation** is only an action taken by the Subscription’s owner, which can sometimes happen long before the Subscription actually lapses. **Expiry**, on the other hand, means that the last paid interval of a Subscription is over.

There is a "Cancel Immediately" option in Commerce, but even this involves a slight delay between the request to cancel and the expiration. Fortunately, Commerce has smoothed over this API for us.

Looking at it from the opposite direction: If we were to revoke permissions in response to the cancellation event, it would mean that users would not benefit from the “real” remainder or balance of their subscriptions.

Let me know if this tracks.
